repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.7'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check .
        pass_filenames: false
        language: python
